FROM httpd:latest

# RUN apt-get install curl \
# && curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - \
# && apt-get update \
# && apt-get install npm \
# && npm install --save-dev video.js \
# && apt-get update \
# && apt-get upgrade